name: Docker Auto Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Approval

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Docker app to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "STEP 1: Go to project directory"
            cd ${{ secrets.EC2_PATH }}

            echo "STEP 2: Pull latest code"
            git stash || true
            git pull

            echo "STEP 3: Stop and remove old container"
            docker stop my-node-app || true
            docker rm my-node-app || true

            echo "STEP 4: Build Docker image"
            docker build -t my-node-app:latest .

            echo "STEP 5: Run new container"
            docker run -d -p 3000:3030 --name my-node-app my-node-app

            echo "Docker deployment completed successfully"

