name: EC2 Auto Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Approval 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to project directory
            cd ${{ secrets.EC2_PATH }}

            # Update code
            git pull

            # STEP 4: Build the project
            npm install --legacy-peer-deps
            npm run build

            # STEP 5: Find the process and kill (Port 3030)
            # Use '|| true' to prevent the script from failing if no process is running
            fuser -k 3030/tcp || true

            # STEP 6: Start the service
            # nohup ensures the process keeps running after the SSH session closes
            nohup npm run start > output.log 2>&1 &
            sleep 2 # Give it a moment to start
            disown



